Generate the mocking framework (a bit)
ZystemOS/pluto pull request #251
Opened 2020-10-05 20:37 UTC by DrDeano

Instead of adding new types in 5 different places, this adds a generation tool that you add the type once and it will be populated in the framework for you.
This is defo one of those over engineered projects, but I had fun making it.

2020-10-06 19:27 UTC, SamTebbs33 requested changes
This is indeed one of the most beautifully over-engineered solutions I have ever seen :D

2020-10-06 19:27 UTC, SamTebbs33 commented on test/gen_types.zig
> +        }
We could probably remove the duplicate code by assigning the big ol' block of spaces to a const and using that.

2020-10-08 23:54 UTC, SamTebbs33 requested changes

2020-10-08 23:54 UTC, SamTebbs33 commented on test/gen_types.zig
>      }
I meant something a bit more like
```
const spaces = if (i == 0) " " ** 4 else " " ** 16;
str = str ++ spaces ++ t[0] ++ intermediate ++ t[1] ++ trail;
```

2020-10-09 10:17 UTC, DrDeano commented on test/gen_types.zig
>      }
Sure

2020-10-09 19:35 UTC, SamTebbs33 approved these changes
lgtm

2020-10-09 23:29 UTC, merged