Add the VMM and page mapping
ZystemOS/pluto pull request #293
Opened 2021-03-10 18:16 UTC by DrDeano

This adds the VMM to kmain_64 along with the ability to map and unmap paged.

This uses level 4 paging, level 5 can be an option in the future.

Paging isn't initialised into the CR3 register yet as this is in the arch init phase.

2021-03-13 16:01 UTC, SamTebbs33 requested changes
Nice one. This looks a hell of a lot more complex than 32 bit

2021-03-13 16:01 UTC, SamTebbs33 commented on src/kernel/arch/x86_64/paging.zig
> +/// Set or clean the attributes from the VMM attributes to the page entry attributes.
clean -> clear

2021-03-13 16:01 UTC, SamTebbs33 commented on src/kernel/arch/x86_64/paging.zig
> +/// Unmap a the address range from start to end from the Page Table.
a the -> an

2021-03-13 16:01 UTC, SamTebbs33 commented on src/kernel/arch/x86_64/paging.zig
> +/// Unmap a the address range from start to end from the Page Directory Pointer Table.
a the -> an

2021-03-13 16:01 UTC, SamTebbs33 commented on src/kernel/arch/x86_64/paging.zig
> +        expectEqual(hasAttribute(val, attr), true);
This could just be `expect(..)`

2021-03-13 16:02 UTC, SamTebbs33 commented
A post-review idea I had was putting some of the function that operator on certain structs (`unmap*Entry`, `map*Entry`, `*Attribute` etc.) inside those structs for some nice encapsulation.

2021-03-17 17:01 UTC, DrDeano commented
Could do, add it as an issue. Then can create a new PR for that

2021-03-19 13:36 UTC, SamTebbs33 approved these changes
Looking gucci

2021-03-19 13:36 UTC, SamTebbs33 commented on src/kernel/arch/x86_64/paging.zig
> +        // PML4 entry 511 and PDPT entry 508 and 511 won't be freed as they are not covered buy the freeing range
buy -> by ;)

2021-03-19 13:36 UTC, SamTebbs33 commented on src/kernel/arch/x86_64/paging.zig
> +        // PML4 entry 511 and PDPT entry 508 and 511 won't be freed as they are not covered buy the freeing range
buy -> by ;)

2021-03-19 16:10 UTC, merged